name: test_bench
description: "A new Flutter project."
version: 0.0.1
homepage: "https://erklabs.com"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  device_frame: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter

  # MIT
  cr_json_widget: ^1.1.1

  # Network
  # MIT
  dio: ^5.4.3+1
  # MIT
  chopper: 7.0.10
  # MIT
  logger: ^2.3.0

  # BSD
  package_info_plus: ^8.0.0

  # MIT
  uuid: ^4.4.0

  # MIT
  app_settings: ^5.1.1

  # BSD
  path_provider: ^2.1.3
  # BSD-3-Clause
  path: ^1.9.0

  # MIT
  inspector: ^2.1.0

  # BSD-3-Clause
  shared_preferences: ^2.2.3
  # MIT
  split_view: ^3.2.1

  # unknown
  # https://pub.dev/packages/synchronized/license
  synchronized: ^3.1.0+1

  # BSD-3-Clause
  js: ^0.7.1

  # BSD-3-Clause
  # https://stackoverflow.com/a/70757512
  platform: ^3.1.4

  # Apache-2.0
  infinite_scroll_pagination: ^4.0.0
  # MIT
  worker_manager: ^7.0.2

  # BSD-2-Clause
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.erk.test_bench
        pluginClass: TestBenchPlugin
      ios:
        pluginClass: TestBenchPlugin
      linux:
        pluginClass: TestBenchPlugin
      macos:
        pluginClass: TestBenchPlugin
      windows:
        pluginClass: TestBenchPluginCApi
      web:
        pluginClass: TestBenchWeb
        fileName: test_bench_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
